### ISSUE TITLE
"Module not found" on Code Splitting branch

### ISSUE THREAD

**Issue by jcleyba** [HarveyD/react-component-library#14]
I've tried the code splitting branch on two different react/typescript projects and I'm always getting
`Module not found: Can't resolve 'react-component-library/build/TestComponent'`

One project is a CRA starter and the other a Next.js starter.

Anyone else with the same problem?

**Comment by HarveyD** [comment]
I'll have a look at this tonight.

**Comment by HarveyD** [comment]
So, it seems the problem is that the `rollup-plugin-postcss` in combination with Rollup code splitting isn't playing nicely. If you look at the build output, it'll have a `src` directory with all the compiled code. All the files in `src` should just be in the top level of `build` directory. 

I'm going to use the `rollup-plugin-sass` plugin on this branch until I can identify what's going wrong with `rollup-plugin-postcss`.

**Comment by HarveyD** [comment]
I've fix the issue on the branch. 

Thank you @jcleyba for raising an issue. You've saved everyone else who was going to use that branch a lot of time!

**Comment by jcleyba** [comment]
Working as a charm! Thanks for the quick fix @HarveyD. I'll close this issue.
