### ISSUE TITLE
[BUG] code splitting error on build

### ISSUE THREAD

**Issue by adnanfajlur** [HarveyD/react-component-library#19]
got incorrect build with `...args` on component

![image](https://user-images.githubusercontent.com/15030247/86215973-83007800-bba7-11ea-989c-1db2a02a56f7.png)

success without `...args`

![image](https://user-images.githubusercontent.com/15030247/86216202-dd99d400-bba7-11ea-94ab-5dbec7205110.png)

thanks

**Comment by HarveyD** [comment]
Okay so after a bit of experimenting, I've found this happens because of the `@rollup/plugin-node-resolve` plugin. 

When Rollup needs to bundle packages from `node_modules`, this plugin will mess up the directory structure of our output. In this case, it's bundling `tslib` (you can see this under `node_modules` in `build`).

To solve this, you can:
- Add `tslib` to the `external` field in `rollup.config.js`, 
- Add it to `peerDependencies` in `package.json` (This will prevent `tslib` from being bundled because of the `peerDepsExternal` plugin.)
- Remove `@rollup/plugin-node-resolve`

I've updated the branch without the `@rollup/plugin-node-resolve` plugin which has fixed the issue. The downside of removing this plugin is that our bundle won't be able to benefit from [Node Resolution Algorithm](https://nodejs.org/api/modules.html#modules_all_together)

**Comment by adnanfajlur** [comment]
it works dude, thanks 😁👌

**Comment by mnlbox** [comment]
@HarveyD Can you explain this?

> The downside of removing this plugin is that our bundle won't be able to benefit from Node Resolution Algorithm.

What we are exactly lost in after remove `resolve()` from plugins for code splitting?
